/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { DropdownOption } from "./components/wc-dropdown/wc-dropdown";
export { DropdownOption } from "./components/wc-dropdown/wc-dropdown";
export namespace Components {
    interface WcButton {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * @default 'primary'
         */
        "variant": 'primary' | 'secondary' | 'danger';
    }
    interface WcCard {
        "heading": string;
        /**
          * @default ''
         */
        "imageAlt": string;
        "imageUrl": string;
        "subtitle": string;
    }
    interface WcDropdown {
        /**
          * @default false
         */
        "disabled": boolean;
        "label": string;
        /**
          * @default []
         */
        "options": DropdownOption[];
        /**
          * @default 'Select an option'
         */
        "placeholder": string;
        /**
          * @default ''
         */
        "value": string;
    }
    interface WcInput {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ''
         */
        "error": string;
        "label": string;
        /**
          * @default ''
         */
        "placeholder": string;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default 'text'
         */
        "type": 'text' | 'email' | 'password' | 'number';
        /**
          * @default ''
         */
        "value": string;
    }
    interface WcToggle {
        /**
          * @default false
         */
        "checked": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        "label": string;
    }
}
export interface WcButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLWcButtonElement;
}
export interface WcDropdownCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLWcDropdownElement;
}
export interface WcInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLWcInputElement;
}
export interface WcToggleCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLWcToggleElement;
}
declare global {
    interface HTMLWcButtonElementEventMap {
        "wcClick": MouseEvent;
    }
    interface HTMLWcButtonElement extends Components.WcButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLWcButtonElementEventMap>(type: K, listener: (this: HTMLWcButtonElement, ev: WcButtonCustomEvent<HTMLWcButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLWcButtonElementEventMap>(type: K, listener: (this: HTMLWcButtonElement, ev: WcButtonCustomEvent<HTMLWcButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLWcButtonElement: {
        prototype: HTMLWcButtonElement;
        new (): HTMLWcButtonElement;
    };
    interface HTMLWcCardElement extends Components.WcCard, HTMLStencilElement {
    }
    var HTMLWcCardElement: {
        prototype: HTMLWcCardElement;
        new (): HTMLWcCardElement;
    };
    interface HTMLWcDropdownElementEventMap {
        "wcSelect": string;
    }
    interface HTMLWcDropdownElement extends Components.WcDropdown, HTMLStencilElement {
        addEventListener<K extends keyof HTMLWcDropdownElementEventMap>(type: K, listener: (this: HTMLWcDropdownElement, ev: WcDropdownCustomEvent<HTMLWcDropdownElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLWcDropdownElementEventMap>(type: K, listener: (this: HTMLWcDropdownElement, ev: WcDropdownCustomEvent<HTMLWcDropdownElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLWcDropdownElement: {
        prototype: HTMLWcDropdownElement;
        new (): HTMLWcDropdownElement;
    };
    interface HTMLWcInputElementEventMap {
        "wcInput": string;
        "wcChange": string;
    }
    interface HTMLWcInputElement extends Components.WcInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLWcInputElementEventMap>(type: K, listener: (this: HTMLWcInputElement, ev: WcInputCustomEvent<HTMLWcInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLWcInputElementEventMap>(type: K, listener: (this: HTMLWcInputElement, ev: WcInputCustomEvent<HTMLWcInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLWcInputElement: {
        prototype: HTMLWcInputElement;
        new (): HTMLWcInputElement;
    };
    interface HTMLWcToggleElementEventMap {
        "wcToggle": boolean;
    }
    interface HTMLWcToggleElement extends Components.WcToggle, HTMLStencilElement {
        addEventListener<K extends keyof HTMLWcToggleElementEventMap>(type: K, listener: (this: HTMLWcToggleElement, ev: WcToggleCustomEvent<HTMLWcToggleElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLWcToggleElementEventMap>(type: K, listener: (this: HTMLWcToggleElement, ev: WcToggleCustomEvent<HTMLWcToggleElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLWcToggleElement: {
        prototype: HTMLWcToggleElement;
        new (): HTMLWcToggleElement;
    };
    interface HTMLElementTagNameMap {
        "wc-button": HTMLWcButtonElement;
        "wc-card": HTMLWcCardElement;
        "wc-dropdown": HTMLWcDropdownElement;
        "wc-input": HTMLWcInputElement;
        "wc-toggle": HTMLWcToggleElement;
    }
}
declare namespace LocalJSX {
    interface WcButton {
        /**
          * @default false
         */
        "disabled"?: boolean;
        "onWcClick"?: (event: WcButtonCustomEvent<MouseEvent>) => void;
        /**
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * @default 'primary'
         */
        "variant"?: 'primary' | 'secondary' | 'danger';
    }
    interface WcCard {
        "heading"?: string;
        /**
          * @default ''
         */
        "imageAlt"?: string;
        "imageUrl"?: string;
        "subtitle"?: string;
    }
    interface WcDropdown {
        /**
          * @default false
         */
        "disabled"?: boolean;
        "label"?: string;
        "onWcSelect"?: (event: WcDropdownCustomEvent<string>) => void;
        /**
          * @default []
         */
        "options"?: DropdownOption[];
        /**
          * @default 'Select an option'
         */
        "placeholder"?: string;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface WcInput {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ''
         */
        "error"?: string;
        "label"?: string;
        "onWcChange"?: (event: WcInputCustomEvent<string>) => void;
        "onWcInput"?: (event: WcInputCustomEvent<string>) => void;
        /**
          * @default ''
         */
        "placeholder"?: string;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default 'text'
         */
        "type"?: 'text' | 'email' | 'password' | 'number';
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface WcToggle {
        /**
          * @default false
         */
        "checked"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        "label"?: string;
        "onWcToggle"?: (event: WcToggleCustomEvent<boolean>) => void;
    }

    interface WcButtonAttributes {
        "variant": 'primary' | 'secondary' | 'danger';
        "disabled": boolean;
        "type": 'button' | 'submit' | 'reset';
    }
    interface WcCardAttributes {
        "heading": string;
        "subtitle": string;
        "imageUrl": string;
        "imageAlt": string;
    }
    interface WcDropdownAttributes {
        "label": string;
        "value": string;
        "placeholder": string;
        "disabled": boolean;
    }
    interface WcInputAttributes {
        "label": string;
        "value": string;
        "type": 'text' | 'email' | 'password' | 'number';
        "placeholder": string;
        "required": boolean;
        "disabled": boolean;
        "error": string;
    }
    interface WcToggleAttributes {
        "label": string;
        "checked": boolean;
        "disabled": boolean;
    }

    interface IntrinsicElements {
        "wc-button": Omit<WcButton, keyof WcButtonAttributes> & { [K in keyof WcButton & keyof WcButtonAttributes]?: WcButton[K] } & { [K in keyof WcButton & keyof WcButtonAttributes as `attr:${K}`]?: WcButtonAttributes[K] } & { [K in keyof WcButton & keyof WcButtonAttributes as `prop:${K}`]?: WcButton[K] };
        "wc-card": Omit<WcCard, keyof WcCardAttributes> & { [K in keyof WcCard & keyof WcCardAttributes]?: WcCard[K] } & { [K in keyof WcCard & keyof WcCardAttributes as `attr:${K}`]?: WcCardAttributes[K] } & { [K in keyof WcCard & keyof WcCardAttributes as `prop:${K}`]?: WcCard[K] };
        "wc-dropdown": Omit<WcDropdown, keyof WcDropdownAttributes> & { [K in keyof WcDropdown & keyof WcDropdownAttributes]?: WcDropdown[K] } & { [K in keyof WcDropdown & keyof WcDropdownAttributes as `attr:${K}`]?: WcDropdownAttributes[K] } & { [K in keyof WcDropdown & keyof WcDropdownAttributes as `prop:${K}`]?: WcDropdown[K] };
        "wc-input": Omit<WcInput, keyof WcInputAttributes> & { [K in keyof WcInput & keyof WcInputAttributes]?: WcInput[K] } & { [K in keyof WcInput & keyof WcInputAttributes as `attr:${K}`]?: WcInputAttributes[K] } & { [K in keyof WcInput & keyof WcInputAttributes as `prop:${K}`]?: WcInput[K] };
        "wc-toggle": Omit<WcToggle, keyof WcToggleAttributes> & { [K in keyof WcToggle & keyof WcToggleAttributes]?: WcToggle[K] } & { [K in keyof WcToggle & keyof WcToggleAttributes as `attr:${K}`]?: WcToggleAttributes[K] } & { [K in keyof WcToggle & keyof WcToggleAttributes as `prop:${K}`]?: WcToggle[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wc-button": LocalJSX.IntrinsicElements["wc-button"] & JSXBase.HTMLAttributes<HTMLWcButtonElement>;
            "wc-card": LocalJSX.IntrinsicElements["wc-card"] & JSXBase.HTMLAttributes<HTMLWcCardElement>;
            "wc-dropdown": LocalJSX.IntrinsicElements["wc-dropdown"] & JSXBase.HTMLAttributes<HTMLWcDropdownElement>;
            "wc-input": LocalJSX.IntrinsicElements["wc-input"] & JSXBase.HTMLAttributes<HTMLWcInputElement>;
            "wc-toggle": LocalJSX.IntrinsicElements["wc-toggle"] & JSXBase.HTMLAttributes<HTMLWcToggleElement>;
        }
    }
}
